title: Apiary RAA Digital Design System
description: Design system for RAA Digital
theme: just-the-docs
url: ./raads-digital

url: https://asmithdigital.github.io/raads-digital/

back_to_top: true
back_to_top_text: "Back to top"

# Collections for website data
collections:
  # foundations:
  #   output: true
  #   permalink: /:collection/:path
  #   folder: _foundations
  # components:
  #   output: true
  #   permalink: /:collection/:path
  #   folder: _components
  # forms:
  #   output: true
  #   permalink: /:collection/:path
  #   folder: _forms
  staffers:
  schedules:
  announcements:

just_the_docs:
  collections:
    # foundations:
    #   name: Foundations
    #   nav_fold: false
    # components:
    #   name: Components
    #   nav_fold: false
    # forms:
    #   name: Forms
    #   nav_fold: false

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

