title: Apiary RAA Digital Design System
description: Design system for RAA Digital
theme: just-the-docs

url: https://asmithdigital.github.io/raads-digital/

logo: "/assets/images/logo.png"

# Collections for website data
collections:
  home:
    output: true
    permalink: /
    folder: /
    sort_by: date
  overview:
    output: true
    permalink: /:collection/:path
    folder: _overview
    sort_by: date
  components:
    output: true
    permalink: /:collection/:path
    folder: _components
    sort_by: date
  staffers:
  schedules:
  announcements:

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    home:
      # Give the collection a name
      name: Test
      nav_fold: False
    overview:
      # Give the collection a name
      name: Overview
      nav_fold: False
    components:
      # Give the collection a name
      name: Components
      nav_fold: False


