title: Apiary RAA Digital Design System
description: Design system for RAA Digital
theme: just-the-docs

url: https://asmithdigital.github.io/raads-digital/

# Collections for website data
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  # overview:
  #   output: true
  #   permalink: /:collection/:path
  #   folder: _docs/_overview
  #   sort_by: date
  # grids:
  #   output: true
  #   permalink: /:collection/:path
  #   folder: _docs/_grids
  #   sort_by: date
  # components:
  #   output: true
  #   permalink: /:collection/:path
  #   folder: _docs/_components
  #   sort_by: date
  staffers:
  schedules:
  announcements:

just_the_docs:
  collections:
    overview:
      name: Overview
      nav_fold: false
    grids:
      name: Layouts
      nav_fold: false
    components:
      name: Components
      nav_fold: false

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

