title: Apiary RAA Digital Design System
description: Design system for RAA Digital
theme: just-the-docs

url: https://asmithdigital.github.io/raads-digital/

aux_links:
  Template Repository: https://github.com/asmithdigital/raads-digital/

collections:
    collection-one:
      permalink: "/:collection/:path/"
      output: true
    collection-two:
      permalink: "/:collection/:path/"
      output: true
  raads_digital:
    collections:
      collection-one:
        name: Collection One
        nav_fold: true
      collection-two:
        name: Collection Two
        nav_fold: false
