title: RAADS digital
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://asmithdigital.github.io/raads-digital/

aux_links:
  Template Repository: https://github.com/asmithdigital/raads-digital/
