title: Apiary RAA Digital Design System
description: Design system for RAA Digital
theme: just-the-docs

url: https://asmithdigital.github.io/raads-digital/

aux_links:
  Template Repository: https://github.com/asmithdigital/raads-digital/

# Collections for website data
collections:
  collection-one:
    output: true
    permalink: /:collection/:path
    folder: _collection-one
    sort_by: date
  staffers:
  schedules:
  announcements:

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    collection-one:
      # Give the collection a name
      name: Collection one
      nav_fold: True
